Tmo.Consts.NETWORK_TAB_CONTACTS = 0;
Tmo.Consts.NETWORK_TAB_ADDRESSES = 1;
Tmo.Consts.NETWORK_TAB_CONTACTS_MAP = 2;
Tmo.Consts.NETWORK_TAB_ADDRESSES_MAP = 3;
Tmo.Consts.NETWORK_TAB_MAPPER = {};
Tmo.Consts.NETWORK_TAB_MAPPER[Tmo.Consts.NETWORK_TAB_CONTACTS] = Tmo.Consts.NETWORK_TAB_CONTACTS;
Tmo.Consts.NETWORK_TAB_MAPPER[Tmo.Consts.NETWORK_TAB_ADDRESSES] = Tmo.Consts.NETWORK_TAB_ADDRESSES;
Tmo.Consts.NETWORK_TAB_MAPPER[Tmo.Consts.NETWORK_TAB_ADDRESSES_MAP] = Tmo.Consts.NETWORK_TAB_CONTACTS_MAP;
Tmo.Consts.NETWORK_TAB_MAPPER[Tmo.Consts.NETWORK_TAB_CONTACTS_MAP] = Tmo.Consts.NETWORK_TAB_CONTACTS_MAP;

Tmo.Consts.SEARCH_TAB_ADDRESSES = 0;
Tmo.Consts.SEARCH_TAB_MEMBERS = 1;
Tmo.Consts.SEARCH_TAB_ADDRESSES_MAP = 2;
Tmo.Consts.SEARCH_TAB_MEMBERS_MAP = 3;
Tmo.Consts.SEARCH_TAB_MAPPER = {};
Tmo.Consts.SEARCH_TAB_MAPPER[Tmo.Consts.SEARCH_TAB_ADDRESSES] = Tmo.Consts.SEARCH_TAB_ADDRESSES;
Tmo.Consts.SEARCH_TAB_MAPPER[Tmo.Consts.SEARCH_TAB_MEMBERS] = Tmo.Consts.SEARCH_TAB_MEMBERS;
Tmo.Consts.SEARCH_TAB_MAPPER[Tmo.Consts.SEARCH_TAB_MEMBERS_MAP] = Tmo.Consts.SEARCH_TAB_ADDRESSES_MAP;
Tmo.Consts.SEARCH_TAB_MAPPER[Tmo.Consts.SEARCH_TAB_ADDRESSES_MAP] = Tmo.Consts.SEARCH_TAB_ADDRESSES_MAP;

